feat: BL-17032 Update PHP to 8.2
dvsa/mot-cpms-notifications pull request #4
Opened 2024-05-28 10:05 UTC by UndermountainK

## Description

Based on [PR 2 - php 8.1 update](https://github.com/dvsa/mot-cpms-notifications/pull/2)

Related issue: [BL-17032](https://dvsa.atlassian.net/browse/BL-17032)

## Before submitting (or marking as "ready for review")

- [x] Does the pull request title follow the [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/) specification?
- [x] Have you performed a self-review of the code?
- [ ] Have you have added tests that prove the fix or feature is effective and working?
- [ ] Did you make sure to update any documentation relating to this change?

2024-06-06 13:39 UTC, mateuszc-kainos requested changes

2024-06-06 13:39 UTC, mateuszc-kainos commented on composer.json
> +        "dvsa/mot-cpms-queues": "dev-feature-bl-17033-php-82-update",
Create a tag in dependency repos and use it here. You can create a tag before merging to master, and after merging you can correct it if needed.

2024-06-06 13:42 UTC, mateuszc-kainos approved these changes

2024-07-25 13:07 UTC, aaronlong approved these changes

2024-07-25 13:07 UTC, merged